### PR TITLE
DBC integrated tests

### PR DESCRIPTION
**Pull request by rasimHZ**
https://github.com/GEOS-DEV/GEOS/pull/2660

### CODE REVIEW

**Comment by rrsettgast** [comment]
@paveltomin I think this needs to be updated?

**Comment by paveltomin** [comment]
> @paveltomin I think this needs to be updated?

Yes, I will try later today

**Comment by CusiniM** [comment]
There are some conflicts in the baselines...

**Comment by paveltomin** [comment]
Thanks, hopefully nothing surprising will pop up

**Comment by CusiniM** [comment]
> Thanks, hopefully nothing surprising will pop up

whenever you fall behind and need to regenerate baselines, IMO it's better if you do a rebase and then force push rather than merging baselines. 

Also, a full layer of the spe10 is way to large for a smoke test. These are supposed to be debuggable cases.

**Review by CusiniM — APPROVED** [review]
I m running them one more time just to make sure.

**Pull request merged**
